updates:
  - package-ecosystem: "gradle"
    directory: "/" 
    schedule:
      day: "saturday"
      interval: "weekly"
      time: "03:00"
    groups:
      dependencies:
        patterns:
          - "*"  
    ignore:
      - dependency-name: "com.vladsch.flexmark:flexmark"
      - dependency-name: "com.arkivanov.essenty:*"
      - dependency-name: "com.arkivanov.decompose:*"
      - dependency-name: "com.squareup.anvil:*"


version: 2
